#  ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://midl.dev
baseurl: ""
title: 
logo: MIDLLOGO.png
email: hello@midl.dev
author: MIDL team
description: > # "Write an awesome description for your new site here. 
  MIDL.dev helps you stake your cryptocurrency and maximize your earnings. You are in full control. Tezos, Polkadot supported.
copyright: 'Copyright &copy; 2023 MIDL.DEV. All Rights Reserved.'
company: 'MIDLDEV OÜ (registry code: 14973249 | registration number EE102369869) | Kentmanni tn 9-43, Tallinn 10116, Estonia'
favicon: "./favicon.ico" # set the favicon of the site
permalink: /:year/:month/:day/:title:output_ext

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
collections:
  frontpage_items:
    output: True
  frontpage_lower_items:
    output: True 
  cryptocurrencies:
    output: True
  operations:
    output: True
  services:
    output: True


exclude:
- bundle
